### PR TITLE
Refactoring & Feature Additions

### PR DESCRIPTION
**Pull request by Systemcluster**
Hello Stefan,

over the holidays I spent a bit of time working on your mod manager. I started with the addition of a few smaller feature I missed, but after noticing the refactoring branch you started, I went over the whole code and refactored it so it is now cleanly organized similar way.

Major changes I made:

- Split up, reorganized and rewrote many parts of the code
  - For the structure I roughly oriented myself by your "refactoringUnitTesting" branch
- Updated 7zip to 18.05 and removed all the unnecessary 7zip files
- When there's a config.ini in the current directory, use that path for storing the config files instead of the user documents, so users can use it in a portable way if they like
- Changed the way user.settings is processed - instead of simply dumping the settings content, the settings are parsed and set with a ConfigParser
- Added a lockfile, so a warning is displayed when more than one instance of the program is opened simultaneously

Smaller features I added:

- Installation of mods by drag-and-drop
- Menu action to open the mod folder directly
- Menu action to refresh load order
- Actions like "show details" or "open folder" now work with multiple selected mods
- "Change priority" dialogs now have the previous value already filled in
- Actions and shortcuts for increase and decrease priority
- Selected mods stay selected when the list refreshes
- Custom ordering for the tree widget so it sorts correctly when ordering by numeric columns
- "Reinstall" action to e.g. reset mod settings
- Mod names are formatted a bit more nicely (e.g. replaces "_" with " ")
- Details window width automatically adjusts to the content width

I probably forgot a thing or two, but you will be able to see all the changes in the commit log. Since this changes your code a lot, I'll understand if you don't want to merge it all at once, but I hope you find at least parts of it useful. 

If there is something to change please let me know. Thanks a lot for creating this tool.

### CODE REVIEW

**Comment by matfax** [comment]
Your PR looks promising. It's kind of sad to see that it never got merged. Have you considered publishing it on Nexusmods on your own?

**Comment by Systemcluster** [comment]
@matfax At the moment I don't plan on publishing it on Nexus Mods. But I'm working on releasing a big update at some point and maybe revisit that idea then. For now I've uploaded my builds [in my GitHub repository](https://github.com/Systemcluster/The-Witcher-3-Mod-manager/releases).

**Comment by matfax** [comment]
@Systemcluster Have you already started your work on this update? Because I would like to work on a patching feature (supplementing the script merges), which also requires refactoring to some degree.

It's unfortunate though that @stefan3372 has not added a license.

**Comment by Systemcluster** [comment]
@matfax Update maybe was't the right word, it's more of a completely new codebase I started a while ago. It's still a good way from completion, but I've just [made it public](https://github.com/Systemcluster/w3modmanager) if you want to take a look at it.

I'm still supporting my fork of Stefan's work nonetheless, so if you want to work on adding a feature to it, feel free to refactor as much as you like. Just open an issue if you have any questions.

**Comment by Systemcluster** [comment]
I think it might make sense to close this PR, since it doesn't seem like this repo has any activity at this point and by now this branch is fairly outdated. I might open another PR from the main branch instead so people at least have a chance to notice it exists.

**Comment by stefan3372** [comment]
Hi, @Systemcluster, thank you for still working on the witcher 3 mod manager, and keeping it's development alive. I started on it sometime ago when i was still not much experienced developer and i wanted to learn python, so yeah the end result wasn't the best and a lot of refactoring needed to be done, hence my refactoring branch.

I don't plan on working on it anymore, but i'll download your release and test it out a bit, as i'm curious. However, yes, this repo is kinda obsolete, so it might make more sense to just focus on your complete rework, as i'm really looking forward to its release!

edit:
ok i played around with it a bit, and it looks pretty solid to me. If this release branch is outdated, you can create one from Main branch as you said and i will merge it and upload it to Nexus if you agree. Just let know your nexus name so i can write who did the update :)

I'm also willing to give you rights to Nexus page, so you can release updates on your own, if would want that

**Comment by stefan3372** [comment]
@Systemcluster ok i played around with it a bit, and it looks pretty solid to me. If this release branch is outdated, you can create one from Main branch as you said and i will merge it and upload it to Nexus if you agree. Just let know your nexus name so i can write who did the update :)

**Comment by Systemcluster** [comment]
@stefan3372 Thank you for the reply! Working on the mod manager was really fun and a great way for me to get used to working with Python and Qt. Your refactoring branch was also a great pointer in the right direction.

Since you don't plan on working on it anymore, I think it makes more sense if I just continue working on it in my repo instead of merging the changes here. I could also give you write access to it if you like. But uploading my release to your Nexus Mods page would be great! My Nexus account is [SullivanMcBlueberry](https://www.nexusmods.com/users/64120341).

I'd also be really happy to get upload access to the page. As I release updates from time to time that would make it much more convenient.

**Comment by stefan3372** [comment]
@Systemcluster All right, I'll upload your newest version then (0.7.7) to Nexus with notes that you'll probably keep on working and updating it, alongside the release notes. Afterwards i'll give you permissions so you can support and update in the future (just don't delete my latest version still on there - 0.6.4 😄). I also saw there are some bugs opened on nexus, so please check if they are still relevant.

P.S. I'll be coming to Nexus page from time to time, to see how things are going 😄 

Edit: Uploaded and permission granted. Could you send me some communication channel of yours so that we keep in touch?

**Comment by Systemcluster** [comment]
@stefan3372 No worries, I'll keep everything intact :) Thanks! You can reach me per mail or on Discord (Chris#8677).

**Comment by MrJudge77** [comment]
@Systemcluster Hi! Chris, what happened to w3modmanager?

**Comment by Systemcluster** [comment]
@MrJudge77 I'll get it back up again soon! I just set it to private for the moment to figure a few things out with the repo configuration.

**Pull request closed without merging**
